config/routes.rb
RestTest::Application.routes.draw do
  resources :hounds
  root :to => "hounds#index"
end

app/models/hound.rb
class Hound < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hounds_controller.rb
class HoundsController < ApplicationController

  respond_to :html, :xml, :json, :yaml

  # GET /hounds
  # GET /hounds.xml
  def index
    @hounds = Hound.all
    respond_with @hounds

#    respond_to do |format|
#      format.html # index.html.erb
#      format.xml  { render :xml => @hounds }
#    end
  end

  # GET /hounds/1
  # GET /hounds/1.xml
  def show
    @hound = Hound.find(params[:id])
    respond_with @hound

#    respond_to do |format|
#      format.html # show.html.erb
#      format.xml  { render :xml => @hound }
#    end
  end

  # GET /hounds/new
  # GET /hounds/new.xml
  def new
    @hound = Hound.new
    respond_with @hound

#    respond_to do |format|
#      format.html # new.html.erb
#      format.xml  { render :xml => @hound }
#    end
  end

  # GET /hounds/1/edit
  def edit
    @hound = Hound.find(params[:id])
    respond_with @hound
  end

  # POST /hounds
  # POST /hounds.xml
  def create
    @hound = Hound.new(params[:hound])
    @hound.save
    respond_with @hound
#    respond_to do |format|
#      if @hound.save
#        format.html { redirect_to(@hound, :notice => 'Hound was successfully created.') }
#        format.xml  { render :xml => @hound, :status => :created, :location => @hound }
#      else
#        format.html { render :action => "new" }
#        format.xml  { render :xml => @hound.errors, :status => :unprocessable_entity }
#      end
#    end
  end

  # PUT /hounds/1
  # PUT /hounds/1.xml
  def update
    @hound = Hound.find(params[:id])

    respond_to do |format|
      if @hound.update_attributes(params[:hound])
        format.html { redirect_to(@hound, :notice => 'Hound was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hound.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hounds/1
  # DELETE /hounds/1.xml
  def destroy
    @hound = Hound.find(params[:id])
    @hound.destroy

    respond_to do |format|
      format.html { redirect_to(hounds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hounds_helper.rb
module HoundsHelper
end

app/views/hounds/_form.html.erb
<%= form_for(@hound) do |f| %>
  <% if @hound.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hound.errors.count, "error") %> prohibited this hound from being saved:</h2>

      <ul>
      <% @hound.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hounds/edit.html.erb
<h1>Editing hound</h1>

<%= render 'form' %>

<%= link_to 'Show', @hound %> |
<%= link_to 'Back', hounds_path %>

app/views/hounds/index.html.erb
<h1>Listing hounds</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hounds.each do |hound| %>
  <tr>
    <td><%= hound.name %></td>
    <td><%= hound.age %></td>
    <td><%= link_to 'Show', hound %></td>
    <td><%= link_to 'Edit', edit_hound_path(hound) %></td>
    <td><%= link_to 'Destroy', hound, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hound', new_hound_path %>

app/views/hounds/new.html.erb
<h1>New hound</h1>

<%= render 'form' %>

<%= link_to 'Back', hounds_path %>

app/views/hounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hound.name %>
</p>

<p>
  <b>Age:</b>
  <%= @hound.age %>
</p>


<%= link_to 'Edit', edit_hound_path(@hound) %> |
<%= link_to 'Back', hounds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestTest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>